gcm_api_key: <%= Rails.application.secrets[:gcm_api_key] %>
http_basic:
  name: <%= Rails.application.secrets[:http_basic][:name] %>
  password: <%= Rails.application.secrets[:http_basic][:password] %>