# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd57b07e845ab073ae54a2436d8ec6f7ec8c0dbaa21d8f3fd187246455fe32d2a4b06f83fe436ed97d12b01fb08cbe175cf553d6a03d73010b4c3941cbeb7008

test:
  secret_key_base: 0e03714f6a18c5edcc0bf0ce72a28d78d78aef0e3eefe81fb8a25e5dd7893b42b71a1a0da275d1d1949564b80fb85eb780ae2ea7f2f75a09433786163b74a43b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
