gcm_api_key: <%= Rails.application.secrets[:gcm_api_key] %>
http_basic:
  name: <%= Rails.application.secrets[:http_basic][:name] %>
  password: <%= Rails.application.secrets[:http_basic][:password] %>
crypto_keyed_hashing:
  fixed_salt: <%= Rails.application.secrets[:crypto_keyed_hashing][:fixed_salt] %>
  fixed_key: <%= Rails.application.secrets[:crypto_keyed_hashing][:fixed_key] %>
