gcm_api_key: AIzaSyBGHPEr4yAWYFyvfEOdyEz3MtPOmLajggw
http_basic:
  name: 47ccf9098174f48be281f86103b9
  password: c5906274ba1a14711a816db53f0d
crypto_keyed_hashing:
  fixed_salt: 6C=rCo#i,$f6j`cC6^o(bb{]}RpErX4kYiG:MEy!3EHxKZK?&@fsB7>GQXqEfu8:w2&z~5{z2M$eb%Y:)u?£^vwG&DN]2+JTM*mNB&Ub5!8xQXVK(>b~6x8?a6b8'3/[
  fixed_key: utq54oD~<Ha<XB~fzkJU,7EndXV4u]4@AijoBiUcPaf%Gf}w5?`HE^X*LX~($LypGu(Ni^GPi;=:jf}3TqZ97giV~5<t5A}^ue=[qAe]`wLY3M&8@c73*duBp5S*~J4b
