<?php

namespace Columba\LocationBundle\Repository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends \Doctrine\ORM\EntityRepository
{
}
